// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Datasets       string
	ProjectUser    string
	Projects       string
	Rights         string
	Roles          string
	RolesHasRights string
	User           string
	WESEndpoints   string
	Workflowrun    string
	Workflows      string
}{
	Datasets:       "Datasets",
	ProjectUser:    "ProjectUser",
	Projects:       "Projects",
	Rights:         "Rights",
	Roles:          "Roles",
	RolesHasRights: "Roles_has_Rights",
	User:           "User",
	WESEndpoints:   "WESEndpoints",
	Workflowrun:    "Workflowrun",
	Workflows:      "Workflows",
}
