// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRights(t *testing.T) {
	t.Parallel()

	query := Rights()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRightsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRightsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Rights().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRightsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RightSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRightsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RightExists(ctx, tx, o.RightID)
	if err != nil {
		t.Errorf("Unable to check if Right exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RightExists to return true, but got false.")
	}
}

func testRightsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	rightFound, err := FindRight(ctx, tx, o.RightID)
	if err != nil {
		t.Error(err)
	}

	if rightFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRightsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Rights().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRightsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Rights().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRightsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	rightOne := &Right{}
	rightTwo := &Right{}
	if err = randomize.Struct(seed, rightOne, rightDBTypes, false, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}
	if err = randomize.Struct(seed, rightTwo, rightDBTypes, false, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rightOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rightTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Rights().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRightsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	rightOne := &Right{}
	rightTwo := &Right{}
	if err = randomize.Struct(seed, rightOne, rightDBTypes, false, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}
	if err = randomize.Struct(seed, rightTwo, rightDBTypes, false, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rightOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rightTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func rightBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func rightAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func rightAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func rightBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func rightAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func rightBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func rightAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func rightBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func rightAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Right) error {
	*o = Right{}
	return nil
}

func testRightsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Right{}
	o := &Right{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, rightDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Right object: %s", err)
	}

	AddRightHook(boil.BeforeInsertHook, rightBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	rightBeforeInsertHooks = []RightHook{}

	AddRightHook(boil.AfterInsertHook, rightAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	rightAfterInsertHooks = []RightHook{}

	AddRightHook(boil.AfterSelectHook, rightAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	rightAfterSelectHooks = []RightHook{}

	AddRightHook(boil.BeforeUpdateHook, rightBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	rightBeforeUpdateHooks = []RightHook{}

	AddRightHook(boil.AfterUpdateHook, rightAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	rightAfterUpdateHooks = []RightHook{}

	AddRightHook(boil.BeforeDeleteHook, rightBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	rightBeforeDeleteHooks = []RightHook{}

	AddRightHook(boil.AfterDeleteHook, rightAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	rightAfterDeleteHooks = []RightHook{}

	AddRightHook(boil.BeforeUpsertHook, rightBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	rightBeforeUpsertHooks = []RightHook{}

	AddRightHook(boil.AfterUpsertHook, rightAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	rightAfterUpsertHooks = []RightHook{}
}

func testRightsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRightsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(rightColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRightToManyRolesRoleIDRoles(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Right
	var b, c Role

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, roleDBTypes, false, roleColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, roleDBTypes, false, roleColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	_, err = tx.Exec("insert into `Roles_has_Rights` (`Rights_RightID`, `Roles_RoleID`) values (?, ?)", a.RightID, b.RoleID)
	if err != nil {
		t.Fatal(err)
	}
	_, err = tx.Exec("insert into `Roles_has_Rights` (`Rights_RightID`, `Roles_RoleID`) values (?, ?)", a.RightID, c.RoleID)
	if err != nil {
		t.Fatal(err)
	}

	check, err := a.RolesRoleIDRoles().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.RoleID == b.RoleID {
			bFound = true
		}
		if v.RoleID == c.RoleID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := RightSlice{&a}
	if err = a.L.LoadRolesRoleIDRoles(ctx, tx, false, (*[]*Right)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RolesRoleIDRoles); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.RolesRoleIDRoles = nil
	if err = a.L.LoadRolesRoleIDRoles(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.RolesRoleIDRoles); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testRightToManyAddOpRolesRoleIDRoles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Right
	var b, c, d, e Role

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rightDBTypes, false, strmangle.SetComplement(rightPrimaryKeyColumns, rightColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Role{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, roleDBTypes, false, strmangle.SetComplement(rolePrimaryKeyColumns, roleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Role{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddRolesRoleIDRoles(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if first.R.RightsRightIDRights[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}
		if second.R.RightsRightIDRights[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}

		if a.R.RolesRoleIDRoles[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.RolesRoleIDRoles[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.RolesRoleIDRoles().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testRightToManySetOpRolesRoleIDRoles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Right
	var b, c, d, e Role

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rightDBTypes, false, strmangle.SetComplement(rightPrimaryKeyColumns, rightColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Role{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, roleDBTypes, false, strmangle.SetComplement(rolePrimaryKeyColumns, roleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetRolesRoleIDRoles(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RolesRoleIDRoles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetRolesRoleIDRoles(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RolesRoleIDRoles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	// The following checks cannot be implemented since we have no handle
	// to these when we call Set(). Leaving them here as wishful thinking
	// and to let people know there's dragons.
	//
	// if len(b.R.RightsRightIDRights) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	// if len(c.R.RightsRightIDRights) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	if d.R.RightsRightIDRights[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}
	if e.R.RightsRightIDRights[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}

	if a.R.RolesRoleIDRoles[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.RolesRoleIDRoles[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testRightToManyRemoveOpRolesRoleIDRoles(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Right
	var b, c, d, e Role

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rightDBTypes, false, strmangle.SetComplement(rightPrimaryKeyColumns, rightColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Role{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, roleDBTypes, false, strmangle.SetComplement(rolePrimaryKeyColumns, roleColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddRolesRoleIDRoles(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.RolesRoleIDRoles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveRolesRoleIDRoles(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.RolesRoleIDRoles().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if len(b.R.RightsRightIDRights) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if len(c.R.RightsRightIDRights) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if d.R.RightsRightIDRights[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.RightsRightIDRights[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if len(a.R.RolesRoleIDRoles) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.RolesRoleIDRoles[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.RolesRoleIDRoles[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testRightsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRightsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RightSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRightsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Rights().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	rightDBTypes = map[string]string{`RightID`: `int`, `RightName`: `varchar`}
	_            = bytes.MinRead
)

func testRightsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(rightPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(rightAllColumns) == len(rightPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rightDBTypes, true, rightPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRightsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(rightAllColumns) == len(rightPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Right{}
	if err = randomize.Struct(seed, o, rightDBTypes, true, rightColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rightDBTypes, true, rightPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(rightAllColumns, rightPrimaryKeyColumns) {
		fields = rightAllColumns
	} else {
		fields = strmangle.SetComplement(
			rightAllColumns,
			rightPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RightSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRightsUpsert(t *testing.T) {
	t.Parallel()

	if len(rightAllColumns) == len(rightPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLRightUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Right{}
	if err = randomize.Struct(seed, &o, rightDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Right: %s", err)
	}

	count, err := Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, rightDBTypes, false, rightPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Right struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Right: %s", err)
	}

	count, err = Rights().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
